- name: Deploy ECS task definition and service
  hosts: localhost

  tasks:
    - set_fact: EcsClusterName="Chatbot"
    - name: create task def- from ansible
      ecs_taskdefinition:
        region: us-east-2
        containers:
        - name: Web-server
          cpu: 10
          essential: true
          image: "wordpress"
          memory: 500
          links:
          - mysql         
          portMappings:
          - containerPort: 80
            hostPort: 80
        - name: phpmyadmin
          cpu: 10
          essential: true
          image: "corbinu/docker-phpmyadmin"
          memory: 500
          links:
          - mysql         
          environment:
          - name: "MYSQL_ROOT_PASSWORD"
            value: "password"
          - name: "MYSQL_USERNAME"
            value: "root"
          portMappings:
          - containerPort: 80
            hostPort: 8181
        - name: mysql
          cpu: 10
          essential: true
          image: "mysql"
          memory: 500                  
          environment:
          - name: "MYSQL_ROOT_PASSWORD"
            value: "password"
        state: present
        family: Chatbot_from_ansible
        # revision: 1
      register: task_output    
   
    - name: Print details name      
      debug: var=task_output.taskdefinition["family"]
    - name: Print details Task revision     
      debug: var=task_output.taskdefinition["revision"]
    - name: Print details Task name and revision     
      debug: 
        msg: "{{  task_output.taskdefinition[\"family\"]   }}:{{ task_output.taskdefinition[\"revision\"] }}"
    
    - name: create ecs service
      ecs_service:
        region: us-east-2
        state: present
        name: wordpress_from_ansible
        cluster: "{{EcsClusterName}}"
        task_definition: "{{  task_output.taskdefinition[\"family\"]   }}:{{ task_output.taskdefinition[\"revision\"] }}"
        desired_count: 1       
      register: service_output
    
    - name: Service Status     
      debug: var=service_output.service.status
    
    - name: Service name 
      debug: var=service_output.service.serviceName

    - name: Service ARN
      debug: var=service_output.service.serviceArn

    - name: Cluster ARN 
      debug: var=service_output.service.clusterArn
      
    - name: create ECS service on VPC network
      ecs_service:
        state: present
        name: wordpress_from_ansible_lb
        cluster: "{{EcsClusterName}}"
        task_definition: "{{  task_output.taskdefinition[\"family\"]   }}:{{ task_output.taskdefinition[\"revision\"] }}"
        desired_count: 0
        load_balancers:
          - targetGroupArn: arn:aws:elasticloadbalancing:us-east-2:769585693008:targetgroup/chatbot-tg/bbca242eb2d78568
            containerName: Web-server
            containerPort: 80
        #network_configuration:
         # subnets:
          #- subnet-7ec6d504
          #security_groups:
          #- sg-002d0a85d94299b69
          #- chatbot-sg
